### ISSUE TITLE
Entity types too strict

### ISSUE THREAD

**Issue by sam-goodwin** [functionless/eventual#408]
This doesn't work:

```ts
export interface StringType {
  type: string;
}

const foo = entity("Foo", {
  partition: ["pk"],
  attributes: {
    pk: z.string(),
    broken: null as any as z.ZodType<StringType>
  }
});
```

```ts
Type 'JSONSchemaType' is not assignable to type 'ZodType<AttributeValue, ZodTypeDef, AttributeValue>'.
  Types of property '_type' are incompatible.
    Type 'StringType' is not assignable to type 'AttributeValue'.
      Type 'StringType' is not assignable to type 'Attributes'.
        Index signature for type 'string' is missing in type 'StringType'.ts(2322)
```

But this does:
```ts
broken: null as any as z.ZodType<{type: string}>
```

**Comment by thantos** [comment]
The type error is [by design in typescript](https://github.com/microsoft/TypeScript/issues/15300). interfaces without a index signature cannot be used as a type that does (ex: Attribute). And the Attribute/AttributeValue type is trying to limit property types to match what dynamo can handle.

Plus the code sample here is a hack that would break if said field was used as a key or we ever generate jsonschema/openai for entities.

Options:
1. close as by design
2. change AttributeValue to `any` and do not type check the definition of the entity attributes.
